"""empty message

Revision ID: 721638624b28
Revises: 2b8fb55edbbd
Create Date: 2023-04-10 04:11:42.853974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '721638624b28'
down_revision = '2b8fb55edbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('photo')
        batch_op.drop_column('createrd_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createrd_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('poster')

    # ### end Alembic commands ###
